# Sartorious experiments data-plotting code

In [1]:
# Importing python packages
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os 

# Importing files
std = '204'
folder = (r"C:\Users\Shivam\Documents\GitHub\viscosity_liquid_transfer_Pablo\Opentrons_experiments\BOTorch_optimization\VS_code_csv")

df_cal = pd.read_csv(folder+r'/Viscosity_std_'+std+'_exp3_withacq.csv')

df_cal.dtypes

liquid              object
pipette             object
volume              object
aspiration_rate    float64
dispense_rate      float64
blow_out_rate        int64
delay_aspirate       int64
delay_dispense       int64
delay_blow_out       int64
%error             float64
time_asp_1000      float64
acq_value          float64
dtype: object

In [2]:
# Calculate time for 1000ul
df_cal['time_for_1000'] = 1000/df_cal["aspiration_rate"] + 1000/df_cal["dispense_rate"] + df_cal["delay_aspirate"] + df_cal["delay_dispense"] + df_cal["delay_blow_out"]
print(df_cal.head())
# Getting unique values of time in a numpy array
TM = df_cal['time_for_1000'].unique()
TM

              liquid pipette                volume  aspiration_rate  \
0  Viscosity_std_204   p1000                1000.0        89.911952
1  Viscosity_std_204   p1000                 500.0        89.911952
2  Viscosity_std_204   p1000                 300.0        89.911952
3  Viscosity_std_204   p1000  mean[300, 500, 1000]        89.911952
4  Viscosity_std_204   p1000                1000.0       112.389940

   dispense_rate  blow_out_rate  delay_aspirate  delay_dispense  \
0      89.911952              0               5               5
1      89.911952              0               5               5
2      89.911952              0               5               5
3      89.911952              0               5               5
4       8.991195              0               5               5

   delay_blow_out     %error  time_asp_1000  acq_value  time_for_1000
0               0 -10.047459      32.243984        NaN      32.243984
1               0  -5.313115      32.243984        NaN      32.243984
2               0  -5.698962      32.243984        NaN      32.243984
3               0  -7.019845      32.243984        NaN      32.243984
4               0   2.812826     130.117512        NaN     130.117512

array([ 32.24398375, 130.11751223,  27.795187  , 232.43983746,
        48.62309007,  56.56025544,  44.482948  ,  48.79111904,
        38.72327839])

In [3]:
# Assigning iterations to each TM value and applying iterations to form a new column in df_cal
iteration = 1
iteration_dict = {}
iteration_list = []

for item in TM:
    iteration_dict[item] = iteration
    iteration += 1
#print(iteration_dict)

count=0
for value in df_cal['time_for_1000']:
    count+=1
    if count>=13 and count<=16:
        iteration_list.append(iteration_dict[value]+2)
        continue
    elif count > 16:
        iteration_list.append(iteration_dict[value]+1)
        continue
    else:
        iteration_list.append(iteration_dict[value])
print(iteration_list)

df_cal['iteration'] = iteration_list
df_cal

[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10]

,liquid,pipette,volume,aspiration_rate,dispense_rate,blow_out_rate,delay_aspirate,delay_dispense,delay_blow_out,%error,time_asp_1000,acq_value,time_for_1000,iteration
0,Viscosity_std_204,p1000,1000.0,89.911952,89.911952,0,5,5,0,-10.047459,32.243984,NaN,32.243984,1
1,Viscosity_std_204,p1000,500.0,89.911952,89.911952,0,5,5,0,-5.313115,32.243984,NaN,32.243984,1
2,Viscosity_std_204,p1000,300.0,89.911952,89.911952,0,5,5,0,-5.698962,32.243984,NaN,32.243984,1
3,Viscosity_std_204,p1000,"mean[300, 500, 1000]",89.911952,89.911952,0,5,5,0,-7.019845,32.243984,NaN,32.243984,1
4,Viscosity_std_204,p1000,1000.0,112.389940,8.991195,0,5,5,0,2.812826,130.117512,NaN,130.117512,2
5,Viscosity_std_204,p1000,500.0,112.389940,8.991195,0,5,5,0,4.734344,130.117512,NaN,130.117512,2
6,Viscosity_std_204,p1000,300.0,112.389940,8.991195,0,5,5,0,3.599954,130.117512,NaN,130.117512,2
7,Viscosity_std_204,p1000,"mean[300, 500, 1000]",112.389940,8.991195,0,5,5,0,-3.715708,130.117512,NaN,130.117512,2
8,Viscosity_std_204,p1000,1000.0,112.389940,112.389940,0,5,5,0,-12.026855,27.795187,NaN,27.795187,3
9,Viscosity_std_204,p1000,500.0,112.389940,112.389940,0,5,5,0,-7.211483,27.795187,NaN,27.795187,3
10,Viscosity_std_204,p1000,300.0,112.389940,112.389940,0,5,5,0,-4.232743,27.795187,NaN,27.795187,3
11,Viscosity_std_204,p1000,"mean[300, 500, 1000]",112.389940,112.389940,0,5,5,0,-7.823694,27.795187,NaN,27.795187,3
12,Viscosity_std_204,p1000,1000.0,8.991195,112.389940,0,5,5,0,-11.193425,130.117512,NaN,130.117512,4
13,Viscosity_std_204,p1000,500.0,8.991195,112.389940,0,5,5,0,-8.160667,130.117512,NaN,130.117512,4
14,Viscosity_std_204,p1000,300.0,8.991195,112.389940,0,5,5,0,-2.071999,130.117512,NaN,130.117512,4
15,Viscosity_std_204,p1000,"mean[300, 500, 1000]",8.991195,112.389940,0,5,5,0,-7.142030,130.117512,NaN,130.117512,4
16,Viscosity_std_204,p1000,1000.0,8.991195,8.991195,0,5,5,0,3.055909,232.439837,NaN,232.439837,5
17,Viscosity_std_204,p1000,500.0,8.991195,8.991195,0,5,5,0,5.151059,232.439837,NaN,232.439837,5
18,Viscosity_std_204,p1000,300.0,8.991195,8.991195,0,5,5,0,8.654551,232.439837,NaN,232.439837,5
19,Viscosity_std_204,p1000,"mean[300, 500, 1000]",8.991195,8.991195,0,5,5,0,-5.620506,232.439837,NaN,232.439837,5
20,Viscosity_std_204,p1000,1000,98.504223,35.123162,0,5,5,0,-2.569742,48.623090,11.030108,48.623090,6
21,Viscosity_std_204,p1000,500,98.504223,35.123162,0,5,5,0,2.210904,48.623090,11.030108,48.623090,6
22,Viscosity_std_204,p1000,300,98.504223,35.123162,0,5,5,0,1.323456,48.623090,11.030108,48.623090,6
23,Viscosity_std_204,p1000,"mean[300, 500, 1000]",98.504223,35.123162,0,5,5,0,-2.034701,48.623090,11.030108,48.623090,6
24,Viscosity_std_204,p1000,1000,78.136789,29.618935,0,5,5,0,-1.296446,56.560255,12.460163,56.560255,7
25,Viscosity_std_204,p1000,500,78.136789,29.618935,0,5,5,0,3.785160,56.560255,12.460163,56.560255,7
26,Viscosity_std_204,p1000,300,78.136789,29.618935,0,5,5,0,2.210904,56.560255,12.460163,56.560255,7
27,Viscosity_std_204,p1000,"mean[300, 500, 1000]",78.136789,29.618935,0,5,5,0,-2.430837,56.560255,12.460163,56.560255,7
28,Viscosity_std_204,p1000,1000,93.316186,42.075689,0,5,5,0,-3.090635,44.482948,11.431273,44.482948,8
29,Viscosity_std_204,p1000,500,93.316186,42.075689,0,5,5,0,0.960759,44.482948,11.431273,44.482948,8
30,Viscosity_std_204,p1000,300,93.316186,42.075689,0,5,5,0,3.329861,44.482948,11.431273,44.482948,8
31,Viscosity_std_204,p1000,"mean[300, 500, 1000]",93.316186,42.075689,0,5,5,0,-2.460418,44.482948,11.431273,44.482948,8
32,Viscosity_std_204,p1000,1000,89.826762,36.155147,0,5,5,0,-2.465563,48.791119,5.187350,48.791119,9
33,Viscosity_std_204,p1000,500,89.826762,36.155147,0,5,5,0,2.280357,48.791119,5.187350,48.791119,9
34,Viscosity_std_204,p1000,300,89.826762,36.155147,0,5,5,0,4.410233,48.791119,5.187350,48.791119,9
35,Viscosity_std_204,p1000,"mean[300, 500, 1000]",89.826762,36.155147,0,5,5,0,-3.052051,48.791119,5.187350,48.791119,9
36,Viscosity_std_204,p1000,1000,110.673791,50.793095,0,5,5,0,-4.294479,38.723278,6.048130,38.723278,10
37,Viscosity_std_204,p1000,500,110.673791,50.793095,0,5,5,0,-0.266235,38.723278,6.048130,38.723278,10
38,Viscosity_std_204,p1000,300,110.673791,50.793095,0,5,5,0,-0.297102,38.723278,6.048130,38.723278,10
39,Viscosity_std_204,p1000,"mean[300, 500, 1000]",110.673791,50.793095,0,5,5,0,-1.619272,38.723278,6.048130,38.723278,10

#### Making a scatterplot

In [4]:
df_cal_mean = df_cal.loc[(df_cal['volume'] == "mean[300, 500, 1000]")]
df_cal_int = df_cal.loc[(df_cal['volume'] != "mean[300, 500, 1000]")]
df_cal_int["volume"] = df_cal_int["volume"].apply(pd.to_numeric)
df_cal_int.dtypes
df_cal_1000 = df_cal_int.loc[(df_cal_int['volume'] == 1000)]
df_cal_500 = df_cal_int.loc[(df_cal_int['volume'] == 500)]
df_cal_300 = df_cal_int.loc[(df_cal_int['volume'] == 300)]
df_cal_100 = df_cal_int.loc[(df_cal_int['volume'] == 100)]

C:\Users\Shivam\AppData\Local\Temp\ipykernel_20472\993082402.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cal_int["volume"] = df_cal_int["volume"].apply(pd.to_numeric)

Empty DataFrame
Columns: [liquid, pipette, volume, aspiration_rate, dispense_rate, blow_out_rate, delay_aspirate, delay_dispense, delay_blow_out, %error, time_asp_1000, acq_value, time_for_1000, iteration]
Index: []

In [ ]:
df_cal_mean.head(10)

In [ ]:
# Making subplots (2 rows, 1 column)
fig,axs = plt.subplots(2,1)

"""# Dropping NAN rows
df_cal_1000 = df_cal.where(df_cal.volume==1000).dropna(how='all')
df_cal_500 = df_cal.where(df_cal.volume==500).dropna(how='all')
df_cal_300 = df_cal.where(df_cal.volume==300).dropna(how='all')
df_cal_100 = df_cal.where(df_cal.volume==100).dropna(how='all')"""

# Plotting graph 1: Iteration against error
axs[0].scatter(df_cal_1000['iteration'],df_cal_1000['%error'], marker= 'x', label = '1000', c = 'red')
axs[0].scatter(df_cal_500['iteration'],df_cal_500['%error'], marker= 'x', label = '500', c = 'green')
axs[0].scatter(df_cal_300['iteration'],df_cal_300['%error'], marker= 'x', label = '300', c = 'blue')
#axs[0].scatter(df_cal_100['iteration'],df_cal_100['%error'], marker= 'x', label = '100', c = 'grey')

# Setting graph 1 labels
axs[0].set_xlabel('Iteration')
axs[0].set_ylabel('Error [%]')

# Plotting graph 2: Iteration against Time
axs[1].scatter(df_cal_1000['iteration'],df_cal_1000['time_for_1000'], marker= 'x', label = '1000', c = 'red')
axs[1].scatter(df_cal_500['iteration'],df_cal_500['time_for_1000'], marker= 'x', label = '500', c = 'green')
axs[1].scatter(df_cal_300['iteration'],df_cal_300['time_for_1000'], marker= 'x', label = '300', c = 'blue')

# Setting graph 2 labels
axs[1].set_xlabel('Iteration')
axs[1].set_ylabel('Time for 1000ul (s)')

#Formatting subplots
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
fig.set_size_inches(17, 10)
fig.suptitle('Viscosity_std_'+std+'_exp3')
axs[0].legend(bbox_to_anchor=(1.1, 1.05))
fig.tight_layout()
axs[0].xaxis.set_major_locator(MultipleLocator(1))
axs[0].xaxis.set_major_formatter('{x:.0f}')
axs[0].axhline(y=0, ls = '--', color = 'black', linewidth=0.5)
axs[1].xaxis.set_major_locator(MultipleLocator(1))
axs[1].xaxis.set_major_formatter('{x:.0f}')

folder1 = (r"C:\Users\Shivam\Documents\GitHub\viscosity_liquid_transfer_Pablo\Opentrons_experiments\BOTorch_optimization\VS_code_csv\graphs")
#fig.savefig(folder1+r'/'+'Viscosity_std_'+std+'_updated.png')

In [ ]:
#Making subplots (2 rows, 1 column)
fig,axs = plt.subplots(2,1)

"""# Dropping NAN rows
df_cal_1000 = df_cal.where(df_cal.volume==1000).dropna(how='all')
df_cal_500 = df_cal.where(df_cal.volume==500).dropna(how='all')
df_cal_300 = df_cal.where(df_cal.volume==300).dropna(how='all')
df_cal_100 = df_cal.where(df_cal.volume==100).dropna(how='all')
"""
# Plotting graph 1: Iteration against error
axs[0].plot(df_cal_1000['iteration'],df_cal_1000['%error'], marker= 'x', label = '1000', c = 'red')
axs[0].plot(df_cal_500['iteration'],df_cal_500['%error'], marker= 'x', label = '500', c = 'green')
axs[0].plot(df_cal_300['iteration'],df_cal_300['%error'], marker= 'x', label = '300', c = 'blue')
#axs[0].plot(df_cal_100['iteration'],df_cal_100['%error'], marker= 'x', label = '100', c = 'grey')

axs[0].set_xlabel('Iteration')
axs[0].set_ylabel('Error [%]')

axs[1].plot(df_cal_1000['iteration'],df_cal_1000['time_for_1000'], marker= 'x', c = 'red')
axs[1].plot(df_cal_500['iteration'],df_cal_500['time_for_1000'], marker= 'x', label = '500', c = 'green')
axs[1].plot(df_cal_300['iteration'],df_cal_300['time_for_1000'], marker= 'x', label = '300', c = 'blue')


axs[1].set_xlabel('Iteration')
axs[1].set_ylabel('Time for 1000ul (s)')

fig.set_size_inches(17, 10)
fig.suptitle('Viscosity_std_'+std+'_exp3')
axs[0].legend(bbox_to_anchor=(1.1, 1.05))
fig.tight_layout()

axs[0].xaxis.set_major_locator(MultipleLocator(1))
axs[0].xaxis.set_major_formatter('{x:.0f}')
axs[0].axhline(y=0, ls = '--', color = 'black', linewidth=0.5)
axs[1].xaxis.set_major_locator(MultipleLocator(1))
axs[1].xaxis.set_major_formatter('{x:.0f}')
#fig.savefig(folder1+r'/'+'Viscosity_std_'+std+'_scatter_updated.png')