In [2]:
import numpy as np
import pandas as pd

In [11]:
# def calc_stats(file_path):    
    # df_experiment = pd.read_csv(r"C:\Users\amdm_\Documents\GitHub\viscosity_liquid_transfer_Pablo\Sartorious_experiments\Experimental_Data\Best_parameters_data\Batch_optimization\Viscosity_std_817_BP_exp3.csv", header=0)
df_experiment = pd.read_csv(r"C:\Users\quijanovelascop\OneDrive - A STAR\Documents\Paper\MOBO_viscous_liquids\Github\Opentrons\Human\Best_parameter_gravimetric_test\Viscosity_std_817_OT2_HO_test.csv", header=0)
df_experiment
calibration_summary(df_experiment)

,Mean transfer volume for 1000 µL [µL],Mean transfer volume error of 1000 µL [µL],Mean relative error for transfer of 1000 µL [%],Standard deviation for transfer of 1000 µL [µL],Relative standard deviation for transfer of 1000 µL [%],Mean transfer volume for 500 µL [µL],Mean transfer volume error of 500 µL [µL],Mean relative error for transfer of 500 µL [%],Standard deviation for transfer of 500 µL [µL],Relative standard deviation for transfer of 500 µL [%],Mean transfer volume for 300 µL [µL],Mean transfer volume error of 300 µL [µL],Mean relative error for transfer of 300 µL [%],Standard deviation for transfer of 300 µL [µL],Relative standard deviation for transfer of 300 µL [%]
3,991.767068,-8.232932,-0.823293,12.858469,1.296521,488.294354,-11.705646,-2.341129,4.650521,0.952401,293.219939,-6.780061,-2.26002,12.335083,4.206768

In [27]:
df_experiment["act_volume"] = (df_experiment["m"] / df_experiment["density"] * 1000)
df_experiment["abs_error"] = (df_experiment["volume"] - df_experiment["act_volume"])
df_experiment["act_time"] = ((df_experiment["volume"] / df_experiment["aspiration_rate"]) + (df_experiment["volume"] / df_experiment["dispense_rate"]) + df_experiment["delay_aspirate"] + df_experiment["delay_dispense"])
df_experiment["percent_error"] = (df_experiment["abs_error"] /(df_experiment["volume"]/100) )
df_experiment

,liquid,pipette,volume,aspiration_rate,dispense_rate,delay_aspirate,delay_dispense,liquid_level,density,m,%error,volume_transfered,volume_error,time_asp_1000,act_volume,abs_error,Time to aspirate 1000 µL [s],percent_error,act_time
0,water,rLine1000,1000,265,265,10,10,46.039453,1,0.980274,-1.972633,980.273668,-19.726332,27.54717,980.273668,19.726332,27.547170,1.972633,27.547170
1,water,rLine1000,1000,265,265,10,10,44.080566,1,0.979443,-2.055689,979.443113,-20.556887,27.54717,979.443113,20.556887,27.547170,2.055689,27.547170
2,water,rLine1000,1000,265,265,10,10,42.087613,1,0.996477,-0.352322,996.476780,-3.523220,27.54717,996.476780,3.523220,27.547170,0.352322,27.547170
3,water,rLine1000,1000,265,265,10,10,40.119051,1,0.984281,-1.571927,984.280733,-15.719267,27.54717,984.280733,15.719267,27.547170,1.571927,27.547170
4,water,rLine1000,1000,265,265,10,10,38.143583,1,0.987734,-1.226591,987.734094,-12.265906,27.54717,987.734094,12.265906,27.547170,1.226591,27.547170
5,water,rLine1000,1000,265,265,10,10,36.175488,1,0.984048,-1.595241,984.047594,-15.952406,27.54717,984.047594,15.952406,27.547170,1.595241,27.547170
6,water,rLine1000,1000,265,265,10,10,34.197805,1,0.988842,-1.115850,988.841501,-11.158499,27.54717,988.841501,11.158499,27.547170,1.115850,27.547170
7,water,rLine1000,1000,265,265,10,10,32.218403,1,0.989701,-1.029880,989.701198,-10.298802,27.54717,989.701198,10.298802,27.547170,1.029880,27.547170
8,water,rLine1000,1000,265,265,10,10,30.242439,1,0.987982,-1.201820,987.981803,-12.018197,27.54717,987.981803,12.018197,27.547170,1.201820,27.547170
9,water,rLine1000,1000,265,265,10,10,28.268341,1,0.987049,-1.295075,987.049250,-12.950750,27.54717,987.049250,12.950750,27.547170,1.295075,27.547170
10,water,rLine1000,500,265,265,10,10,27.281204,1,0.493568,-1.286332,493.568338,-6.431662,27.54717,493.568338,6.431662,23.773585,1.286332,23.773585
11,water,rLine1000,500,265,265,10,10,26.292581,1,0.494311,-1.137707,494.311467,-5.688533,27.54717,494.311467,5.688533,23.773585,1.137707,23.773585
12,water,rLine1000,500,265,265,10,10,25.318966,1,0.486807,-2.638534,486.807328,-13.192672,27.54717,486.807328,13.192672,23.773585,2.638534,23.773585
13,water,rLine1000,500,265,265,10,10,24.351617,1,0.483675,-3.265094,483.674532,-16.325468,27.54717,483.674532,16.325468,23.773585,3.265094,23.773585
14,water,rLine1000,500,265,265,10,10,23.393244,1,0.479187,-4.162676,479.186620,-20.813380,27.54717,479.186620,20.813380,23.773585,4.162676,23.773585
15,water,rLine1000,500,265,265,10,10,22.402202,1,0.495521,-0.895826,495.520872,-4.479128,27.54717,495.520872,4.479128,23.773585,0.895826,23.773585
16,water,rLine1000,500,265,265,10,10,21.440623,1,0.480789,-3.842111,480.789446,-19.210554,27.54717,480.789446,19.210554,23.773585,3.842111,23.773585
17,water,rLine1000,500,265,265,10,10,20.466921,1,0.486851,-2.629792,486.851041,-13.148959,27.54717,486.851041,13.148959,23.773585,2.629792,23.773585
18,water,rLine1000,500,265,265,10,10,19.502341,1,0.482290,-3.541945,482.290273,-17.709727,27.54717,482.290273,17.709727,23.773585,3.541945,23.773585
19,water,rLine1000,500,265,265,10,10,18.525404,1,0.488468,-2.306312,488.468438,-11.531562,27.54717,488.468438,11.531562,23.773585,2.306312,23.773585
20,water,rLine1000,300,265,265,10,10,17.952175,1,0.286614,-4.461870,286.614390,-13.385610,27.54717,286.614390,13.385610,22.264151,4.461870,22.264151
21,water,rLine1000,300,265,265,10,10,17.374546,1,0.288815,-3.728456,288.814632,-11.185368,27.54717,288.814632,11.185368,22.264151,3.728456,22.264151
22,water,rLine1000,300,265,265,10,10,16.786046,1,0.294250,-1.916777,294.249669,-5.750331,27.54717,294.249669,5.750331,22.264151,1.916777,22.264151
23,water,rLine1000,300,265,265,10,10,16.169745,1,0.308151,2.716846,308.150539,8.150539,27.54717,308.150539,-8.150539,22.264151,-2.716846,22.264151
24,water,rLine1000,300,265,265,10,10,15.582936,1,0.293405,-2.198486,293.404542,-6.595458,27.54717,293.404542,6.595458,22.264151,2.198486,22.264151
25,water,rLine1000,300,265,265,10,10,15.030719,1,0.276109,-7.963802,276.108595,-23.891405,27.54717,276.108595,23.891405,22.264151,7.963802,22.264151
26,water,rLine1000,300,265,265,10,10,14.458947,1,0.285886,-4.704723,285.885832,-14.114168,27.54717,285.885832,14.114168,22.264151,4.704723,22.264151
27,water,rLine1000,300,265,265,10,10,13.883300,1,0.287824,-4.058735,287.823794,-12.176206,27.54717,287.823794,12.176206,22.264151,4.058735,22.264151
28,water,rLine1000,300,265,265,10,10,13.318260,1,0.282520,-5.826701,282.519898,-17.480102,27.54717,282.519898,17.480102,22.264151,5.826701,22.264151
29,water,rLine1000,300,265,265,10,10,12.724661,1,0.296800,-1.066794,296.799619,-3.200381,27.54717,296.799619,3.200381,22.264151,1.066794,22.264151

In [28]:
df_summary_all = pd.DataFrame()
for x in df_experiment['volume'].unique():
    df_experiment_1000 = df_experiment.where(df_experiment['volume'] == x).dropna(how='all')
    df_summary = pd.DataFrame(columns = (f'{x} Actual Volume', f'{x} Absolute Error', f'{x} Percentage Error', f'{x} Actual Time', f'{x} Std Dev', f'{x} Relative Std Dev') )
    data = [df_experiment_1000['act_volume'].mean(), df_experiment_1000['abs_error'].mean(), df_experiment_1000['percent_error'].mean(), df_experiment_1000['act_time'].mean(), df_experiment_1000['act_volume'].std(), (df_experiment_1000['act_volume'].std() / df_experiment_1000['act_volume'].mean() * 100)]
    df_summary.loc[df_experiment['liquid'].iloc[0]] = data
    df_summary_all = pd.concat([df_summary_all, df_summary], axis = 1)

In [5]:
def calibration_summary(df):

    if 'volume_transfered' and 'volume_error' and 'time_asp_1000' not in df.columns:
        df['volume_transfered'] = (df['m']/df['density'])*1000
        df['volume_error'] = df['volume_transfered'] - df['volume']
        df['time_asp_1000']=1000/df['aspiration_rate'] + 1000/df['dispense_rate'] + df['delay_aspirate'] + df['delay_dispense']             

    df_summary_all = pd.DataFrame()

    for volume in df['volume'].unique():
        df_experiment_v = df.where(df['volume'] == volume).dropna(how='all')
        df_summary = pd.DataFrame(columns = (f'Mean transfer volume for {volume} µL [µL]', f'Mean transfer volume error of {volume} µL [µL]', f'Mean relative error for transfer of {volume} µL [%]', f'Standard deviation for transfer of {volume} µL [µL]', f'Relative standard deviation for transfer of {volume} µL [%]') )
        data = [df_experiment_v['volume_transfered'].mean(), df_experiment_v['volume_error'].mean(), df_experiment_v['%error'].mean(), df_experiment_v['volume_transfered'].std(), (df_experiment_v['volume_transfered'].std() / df_experiment_v['volume_transfered'].mean() * 100)]
        df_summary.loc[df['liquid'].iloc[0]] = data
        df_summary_all = pd.concat([df_summary_all, df_summary], axis = 1)
    return df_summary_all

In [30]:
calibration_summary(df_experiment).to_csv('water_calibration_summary.csv')

In [29]:
df_summary_all

,1000 Actual Volume,1000 Absolute Error,1000 Percentage Error,1000 Actual Time,1000 Std Dev,1000 Relative Std Dev,500 Actual Volume,500 Absolute Error,500 Percentage Error,500 Actual Time,500 Std Dev,500 Relative Std Dev,300 Actual Volume,300 Absolute Error,300 Percentage Error,300 Actual Time,300 Std Dev,300 Relative Std Dev
water,986.582973,13.417027,1.341703,27.54717,4.929777,0.499682,487.146836,12.853165,2.570633,23.773585,5.812497,1.193171,290.037151,9.962849,3.32095,22.264151,8.74812,3.016207